var tableNum = prompt("Enter number to find table",5);
var tableNum2 = parseInt(tableNum);
document.write(tableNum2 + " *  1" + " = " + tableNum2*1);
document.write("<br />");
document.write(tableNum2 + " *  2" + " = " + tableNum2*2);
document.write("<br />");
document.write(tableNum2 + " *  3" + " = " + tableNum2*3);
document.write("<br />");
document.write(tableNum2 + " *  4" + " = " + tableNum2*4);
document.write("<br />");
document.write(tableNum2 + " *  5" + " = " + tableNum2*5);
document.write("<br />");
document.write(tableNum2 + " *  6" + " = " + tableNum2*6);
document.write("<br />");
document.write(tableNum2 + " *  7" + " = " + tableNum2*7);
document.write("<br />");
document.write(tableNum2 + " *  8" + " = " + tableNum2*8);
document.write("<br />");
document.write(tableNum2 + " *  9" + " = " + tableNum2*9);
document.write("<br />");
document.write(tableNum2 + " *  10" + " = " + tableNum2*10);
document.write("<br />");
